main: net.tfminecraft.cooking.Cooking
api-version: 1.21
name: Cooking
version: ${project.version}
author: Drefvelin

depend: [TLibs, InteractibleFurniture, TFMCCore]
softdepend: [RPCharacters, MMOCore, CustomCrops, SimpleFactions, CustomFishing]

commands:
  cooking:
    description: Cooking admin/debug commands
    usage: /cooking reload | /cooking builditem <string> | /cooking preview <target> ...
    permission: cooking.admin

permissions:
  cooking.admin:
    description: Admin access to all Cooking commands
    default: op
